version: "3.9"

services:
  auth_api:
    build:
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
      target: develop
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ../../:/usr/src/auth_app
